//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "InteropAPI.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    Library_InteropAPI_Microsoft_SPOT_InteropAPI_API::NativeOperation___STATIC__I4__I4__I4__U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Microsoft_SPOT_InteropAPI =
{
    "Microsoft_SPOT_InteropAPI", 
    0x44410F6B,
    method_lookup
};

