//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _INTEROPAPI_H_
#define _INTEROPAPI_H_

#include <TinyCLR_Interop.h>
struct Library_InteropAPI_Microsoft_SPOT_InteropAPI_API
{
    static const int FIELD__result = 1;
    static const int FIELD__resultValid = 2;

    TINYCLR_NATIVE_DECLARE(NativeOperation___STATIC__I4__I4__I4__U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Microsoft_SPOT_InteropAPI;

#endif  //_INTEROPAPI_H_
