//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Xml;
using System.Ext;
using System.Ext.Xml;
using Ws.ServiceModel;
using Ws.Services.Mtom;
using Ws.Services.Serialization;
using XmlElement = Ws.Services.Xml.WsXmlNode;
using XmlAttribute = Ws.Services.Xml.WsXmlAttribute;
using XmlConvert = Ws.Services.Serialization.WsXmlConvert;

namespace schemas.example.org.SimpleService
{
    
    
    [DataContract(Namespace="http://schemas.example.org/SimpleService")]
    public class OneWayRequest
    {
        
        [DataMember(Order=0, IsNillable=true)]
        public int Param;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlElement[] Any;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlAttribute[] AnyAttr;
    }
    
    public class OneWayRequestDataContractSerializer : DataContractSerializer
    {
        
        public OneWayRequestDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public OneWayRequestDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            OneWayRequest OneWayRequestField = null;
            if (IsParentStartElement(reader, false, true))
            {
                OneWayRequestField = new OneWayRequest();
                OneWayRequestField.AnyAttr = ReadAnyAttribute(reader);
                reader.Read();
                if (IsChildStartElement(reader, "Param", true, true))
                {
                    reader.Read();
                    OneWayRequestField.Param = XmlConvert.ToInt32(reader.ReadString());
                    reader.ReadEndElement();
                }
                OneWayRequestField.Any = ReadAnyElement(reader, false);
                reader.ReadEndElement();
            }
            return OneWayRequestField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            OneWayRequest OneWayRequestField = ((OneWayRequest)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                WriteAnyAttribute(writer, OneWayRequestField.AnyAttr);
                if (WriteChildElement(writer, "Param", true, true, OneWayRequestField.Param))
                {
                    writer.WriteString(XmlConvert.ToString(OneWayRequestField.Param));
                    writer.WriteEndElement();
                }
                WriteAnyElement(writer, OneWayRequestField.Any, false);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.example.org/SimpleService")]
    public class TwoWayRequest
    {
        
        [DataMember(Order=0, IsNillable=true)]
        public int X;
        
        [DataMember(Order=1, IsNillable=true)]
        public int Y;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlElement[] Any;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlAttribute[] AnyAttr;
    }
    
    public class TwoWayRequestDataContractSerializer : DataContractSerializer
    {
        
        public TwoWayRequestDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public TwoWayRequestDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            TwoWayRequest TwoWayRequestField = null;
            if (IsParentStartElement(reader, false, true))
            {
                TwoWayRequestField = new TwoWayRequest();
                TwoWayRequestField.AnyAttr = ReadAnyAttribute(reader);
                reader.Read();
                if (IsChildStartElement(reader, "X", true, true))
                {
                    reader.Read();
                    TwoWayRequestField.X = XmlConvert.ToInt32(reader.ReadString());
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "Y", true, true))
                {
                    reader.Read();
                    TwoWayRequestField.Y = XmlConvert.ToInt32(reader.ReadString());
                    reader.ReadEndElement();
                }
                TwoWayRequestField.Any = ReadAnyElement(reader, false);
                reader.ReadEndElement();
            }
            return TwoWayRequestField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            TwoWayRequest TwoWayRequestField = ((TwoWayRequest)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                WriteAnyAttribute(writer, TwoWayRequestField.AnyAttr);
                if (WriteChildElement(writer, "X", true, true, TwoWayRequestField.X))
                {
                    writer.WriteString(XmlConvert.ToString(TwoWayRequestField.X));
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "Y", true, true, TwoWayRequestField.Y))
                {
                    writer.WriteString(XmlConvert.ToString(TwoWayRequestField.Y));
                    writer.WriteEndElement();
                }
                WriteAnyElement(writer, TwoWayRequestField.Any, false);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.example.org/SimpleService")]
    public class TwoWayResponse
    {
        
        [DataMember(Order=0, IsNillable=true)]
        public int Sum;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlElement[] Any;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlAttribute[] AnyAttr;
    }
    
    public class TwoWayResponseDataContractSerializer : DataContractSerializer
    {
        
        public TwoWayResponseDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public TwoWayResponseDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            TwoWayResponse TwoWayResponseField = null;
            if (IsParentStartElement(reader, false, true))
            {
                TwoWayResponseField = new TwoWayResponse();
                TwoWayResponseField.AnyAttr = ReadAnyAttribute(reader);
                reader.Read();
                if (IsChildStartElement(reader, "Sum", true, true))
                {
                    reader.Read();
                    TwoWayResponseField.Sum = XmlConvert.ToInt32(reader.ReadString());
                    reader.ReadEndElement();
                }
                TwoWayResponseField.Any = ReadAnyElement(reader, false);
                reader.ReadEndElement();
            }
            return TwoWayResponseField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            TwoWayResponse TwoWayResponseField = ((TwoWayResponse)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                WriteAnyAttribute(writer, TwoWayResponseField.AnyAttr);
                if (WriteChildElement(writer, "Sum", true, true, TwoWayResponseField.Sum))
                {
                    writer.WriteString(XmlConvert.ToString(TwoWayResponseField.Sum));
                    writer.WriteEndElement();
                }
                WriteAnyElement(writer, TwoWayResponseField.Any, false);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.example.org/SimpleService")]
    public class TypeCheckRequest
    {
        
        [DataMember(Order=0, IsNillable=true)]
        public bool BoolCheck;
        
        [DataMember(Order=1, IsNillable=true)]
        public string DecimalCheck;
        
        [DataMember(Order=2, IsNillable=true)]
        public float FloatCheck;
        
        [DataMember(Order=3, IsNillable=true)]
        public string[] UriListCheck;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlElement[] Any;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlAttribute[] AnyAttr;
    }
    
    public class TypeCheckRequestDataContractSerializer : DataContractSerializer
    {
        
        public TypeCheckRequestDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public TypeCheckRequestDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            TypeCheckRequest TypeCheckRequestField = null;
            if (IsParentStartElement(reader, false, true))
            {
                TypeCheckRequestField = new TypeCheckRequest();
                TypeCheckRequestField.AnyAttr = ReadAnyAttribute(reader);
                reader.Read();
                if (IsChildStartElement(reader, "BoolCheck", true, true))
                {
                    reader.Read();
                    TypeCheckRequestField.BoolCheck = XmlConvert.ToBoolean(reader.ReadString());
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "DecimalCheck", true, true))
                {
                    reader.Read();
                    TypeCheckRequestField.DecimalCheck = reader.ReadString();
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "FloatCheck", true, true))
                {
                    reader.Read();
                    TypeCheckRequestField.FloatCheck = XmlConvert.ToSingle(reader.ReadString());
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "UriListCheck", true, true))
                {
                    reader.Read();
                    string[] UriListCheck_List = reader.ReadString().Split();
                    TypeCheckRequestField.UriListCheck = new string[UriListCheck_List.Length];
                    for (int i = 0; (i < UriListCheck_List.Length); i = (i + 1))
                    {
                        TypeCheckRequestField.UriListCheck[i] = UriListCheck_List[i];
                    }
                    reader.ReadEndElement();
                }
                TypeCheckRequestField.Any = ReadAnyElement(reader, false);
                reader.ReadEndElement();
            }
            return TypeCheckRequestField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            TypeCheckRequest TypeCheckRequestField = ((TypeCheckRequest)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                WriteAnyAttribute(writer, TypeCheckRequestField.AnyAttr);
                if (WriteChildElement(writer, "BoolCheck", true, true, TypeCheckRequestField.BoolCheck))
                {
                    writer.WriteString(XmlConvert.ToString(TypeCheckRequestField.BoolCheck));
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "DecimalCheck", true, true, TypeCheckRequestField.DecimalCheck))
                {
                    writer.WriteString(TypeCheckRequestField.DecimalCheck);
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "FloatCheck", true, true, TypeCheckRequestField.FloatCheck))
                {
                    writer.WriteString(XmlConvert.ToString(TypeCheckRequestField.FloatCheck));
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "UriListCheck", true, true, TypeCheckRequestField.UriListCheck))
                {
                    string UriListCheck_List = "";
                    for (int i = 0; (i < TypeCheckRequestField.UriListCheck.Length); i = (i + 1))
                    {
                        UriListCheck_List = (UriListCheck_List + TypeCheckRequestField.UriListCheck[i]);
                        if ((i 
                                    < (TypeCheckRequestField.UriListCheck.Length - 1)))
                        {
                            UriListCheck_List = (UriListCheck_List + " ");
                        }
                    }
                    writer.WriteString(UriListCheck_List);
                    writer.WriteEndElement();
                }
                WriteAnyElement(writer, TypeCheckRequestField.Any, false);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.example.org/SimpleService")]
    public class TypeCheckResponse
    {
        
        [DataMember(Order=0, IsNillable=true)]
        public bool BoolCheck;
        
        [DataMember(Order=1, IsNillable=true)]
        public string DecimalCheck;
        
        [DataMember(Order=2, IsNillable=true)]
        public float FloatCheck;
        
        [DataMember(Order=3, IsNillable=true)]
        public string[] UriListCheck;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlElement[] Any;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlAttribute[] AnyAttr;
    }
    
    public class TypeCheckResponseDataContractSerializer : DataContractSerializer
    {
        
        public TypeCheckResponseDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public TypeCheckResponseDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            TypeCheckResponse TypeCheckResponseField = null;
            if (IsParentStartElement(reader, false, true))
            {
                TypeCheckResponseField = new TypeCheckResponse();
                TypeCheckResponseField.AnyAttr = ReadAnyAttribute(reader);
                reader.Read();
                if (IsChildStartElement(reader, "BoolCheck", true, true))
                {
                    reader.Read();
                    TypeCheckResponseField.BoolCheck = XmlConvert.ToBoolean(reader.ReadString());
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "DecimalCheck", true, true))
                {
                    reader.Read();
                    TypeCheckResponseField.DecimalCheck = reader.ReadString();
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "FloatCheck", true, true))
                {
                    reader.Read();
                    TypeCheckResponseField.FloatCheck = XmlConvert.ToSingle(reader.ReadString());
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "UriListCheck", true, true))
                {
                    reader.Read();
                    string[] UriListCheck_List = reader.ReadString().Split();
                    TypeCheckResponseField.UriListCheck = new string[UriListCheck_List.Length];
                    for (int i = 0; (i < UriListCheck_List.Length); i = (i + 1))
                    {
                        TypeCheckResponseField.UriListCheck[i] = UriListCheck_List[i];
                    }
                    reader.ReadEndElement();
                }
                TypeCheckResponseField.Any = ReadAnyElement(reader, false);
                reader.ReadEndElement();
            }
            return TypeCheckResponseField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            TypeCheckResponse TypeCheckResponseField = ((TypeCheckResponse)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                WriteAnyAttribute(writer, TypeCheckResponseField.AnyAttr);
                if (WriteChildElement(writer, "BoolCheck", true, true, TypeCheckResponseField.BoolCheck))
                {
                    writer.WriteString(XmlConvert.ToString(TypeCheckResponseField.BoolCheck));
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "DecimalCheck", true, true, TypeCheckResponseField.DecimalCheck))
                {
                    writer.WriteString(TypeCheckResponseField.DecimalCheck);
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "FloatCheck", true, true, TypeCheckResponseField.FloatCheck))
                {
                    writer.WriteString(XmlConvert.ToString(TypeCheckResponseField.FloatCheck));
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "UriListCheck", true, true, TypeCheckResponseField.UriListCheck))
                {
                    string UriListCheck_List = "";
                    for (int i = 0; (i < TypeCheckResponseField.UriListCheck.Length); i = (i + 1))
                    {
                        UriListCheck_List = (UriListCheck_List + TypeCheckResponseField.UriListCheck[i]);
                        if ((i 
                                    < (TypeCheckResponseField.UriListCheck.Length - 1)))
                        {
                            UriListCheck_List = (UriListCheck_List + " ");
                        }
                    }
                    writer.WriteString(UriListCheck_List);
                    writer.WriteEndElement();
                }
                WriteAnyElement(writer, TypeCheckResponseField.Any, false);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.example.org/SimpleService")]
    public class AnyCheckRequest
    {
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlElement[] Any;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlAttribute[] AnyAttr;
    }
    
    public class AnyCheckRequestDataContractSerializer : DataContractSerializer
    {
        
        public AnyCheckRequestDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public AnyCheckRequestDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            AnyCheckRequest AnyCheckRequestField = null;
            if (IsParentStartElement(reader, false, true))
            {
                AnyCheckRequestField = new AnyCheckRequest();
                AnyCheckRequestField.AnyAttr = ReadAnyAttribute(reader);
                reader.Read();
                AnyCheckRequestField.Any = ReadAnyElement(reader, false);
                reader.ReadEndElement();
            }
            return AnyCheckRequestField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            AnyCheckRequest AnyCheckRequestField = ((AnyCheckRequest)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                WriteAnyAttribute(writer, AnyCheckRequestField.AnyAttr);
                WriteAnyElement(writer, AnyCheckRequestField.Any, false);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.example.org/SimpleService")]
    public class AnyCheckResponse
    {
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlElement[] Any;
        
        [DataMember(IsNillable=true, IsRequired=false)]
        public XmlAttribute[] AnyAttr;
    }
    
    public class AnyCheckResponseDataContractSerializer : DataContractSerializer
    {
        
        public AnyCheckResponseDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public AnyCheckResponseDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            AnyCheckResponse AnyCheckResponseField = null;
            if (IsParentStartElement(reader, false, true))
            {
                AnyCheckResponseField = new AnyCheckResponse();
                AnyCheckResponseField.AnyAttr = ReadAnyAttribute(reader);
                reader.Read();
                AnyCheckResponseField.Any = ReadAnyElement(reader, false);
                reader.ReadEndElement();
            }
            return AnyCheckResponseField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            AnyCheckResponse AnyCheckResponseField = ((AnyCheckResponse)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                WriteAnyAttribute(writer, AnyCheckResponseField.AnyAttr);
                WriteAnyElement(writer, AnyCheckResponseField.Any, false);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [ServiceContract(Namespace="http://schemas.example.org/SimpleService")]
    [PolicyAssertion(Namespace="http://schemas.xmlsoap.org/ws/2006/02/devprof", Name="profile", PolicyID="SimpleServicePolicy")]
    public interface ISimpleService
    {
        
        [OperationContract(Action="http://schemas.example.org/SimpleService/OneWay", IsOneWay=true)]
        void OneWay(OneWayRequest req);
        
        [OperationContract(Action="http://schemas.example.org/SimpleService/TwoWay")]
        TwoWayResponse TwoWay(TwoWayRequest req);
        
        [OperationContract(Action="http://schemas.example.org/SimpleService/TypeCheck")]
        TypeCheckResponse TypeCheck(TypeCheckRequest req);
        
        [OperationContract(Action="http://schemas.example.org/SimpleService/AnyCheck")]
        AnyCheckResponse AnyCheck(AnyCheckRequest req);
    }
}
