//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _MP3DECODER_H_
#define _MP3DECODER_H_

#include <TinyCLR_Interop.h>
struct Library_Mp3Decoder_NXP_Interop_MP3Decoder
{
    static const int FIELD__inBuffer = 1;
    static const int FIELD__bytesLeft = 2;
    static const int FIELD__readIndex = 3;

    TINYCLR_NATIVE_DECLARE(FindNextFrameStart___VOID__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(NativeMP3Decode___VOID__SZARRAY_U1__BYREF_I2);
    TINYCLR_NATIVE_DECLARE(InitHelixDecoder___VOID);
    TINYCLR_NATIVE_DECLARE(UninitHelixDecoder___VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Mp3Decoder;

#endif  //_MP3DECODER_H_
