/*
|  RTPHWIO.H - Runtime Platform String Library
| 
|  EBSnet - 								
| 
|   $Author: sarah $
|   $Date: 2005/05/14 02:43:30 $
|   $Name:  $
|   $Revision: 1.1 $
| 
|  Copyright EBSnet Inc. , 2004
|  All rights reserved.
|  This code may not be redistributed in source or linkable object form
|  without the consent of its author.
*/ 

#ifndef __RTPHWIO_H__
#define __RTPHWIO_H__

void    rtp_io_delay(void);

#define OUTBYTE(ADD, VAL)  
#define OUTWORD(ADD, VAL)  
#define OUTDWORD(ADD, VAL) 
#define INBYTE(ADD)        1
#define INWORD(ADD)        1
#define INDWORD(ADD)       1


#endif /* __RTPHWIO_H__ */
