/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.cpp                                           */
/*  DATE        :Wed, Apr 22, 2009                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :SH7619                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif

#define SDMR3           (*(volatile short *)0xf8fd5880)
#define RAM_Clear       (*(volatile long  *)0xAC000000)

#pragma section ResetPRG

void HardwareSetup(void)
{
    int addr;
    
/* PORT settings */
    PFC.PACRH1.WORD = 0x0005;
    PFC.PACRH2.WORD = 0x5555;
    PFC.PBCRL1.WORD = 0x0501;
    PFC.PBCRL2.WORD = 0x1554;
    PFC.PBIORL.WORD = 0x0E82;
    PFC.PDCRL2.WORD = 0x28A1;
    PFC.PDIORL.WORD = 0x009A;
    PFC.PECRH1.WORD = 0x0003;
    PFC.PECRH2.WORD = 0xffff;
    PFC.PECRL1.WORD = 0xfffc;
    PFC.PECRL2.WORD = 0x2222;
    PFC.PEIORL.WORD = 0x012A;
/* WDT setting */
    WDT.WRITE.WTCSR = 0xA502;
/* CPG setting */
    CPG.FRQCR.WORD = 0x1103;
/* Cache setting */
    CCR1.LONG      = 0x0000090b;
/* BSC settings */
    BSC.CMNCR.LONG = 0x00001014;
    BSC.CS0BCR.LONG = 0x24920000;
    BSC.CS3BCR.LONG = 0x12494600;
    BSC.CS4BCR.LONG = 0x24920400;
    BSC.CS5BBCR.LONG = 0x36db0600;
    BSC.CS6BBCR.LONG = 0x12490400;
    BSC.CS0WCR = 0x00000300;
    BSC.CS3WCR = 0x0000248A;
    BSC.CS4WCR = 0x00000380;
    BSC.CS5BWCR = 0x00000500;
    BSC.CS6BWCR = 0x00001D03;
/* AutoRefresh for SDRAM turned ON */
    BSC.SDCR.LONG = 0x00000800;
    BSC.RTCNT = 0xa55a0000;
    BSC.RTCOR = 0xa55a003a;
    BSC.RTCSR.LONG = 0xa55a0014;
/*  SDMR3.word = 0x0000; (address f8fd5880)*/
    SDMR3 = 0x0000;

    addr = 0xAC008000;
    (*(volatile long *)addr) = 0xA50F0FA5;
    int tmp = 0x12345678;
    tmp = 0x0;
    tmp += *(volatile long *)addr;
    if(tmp!=0xA50F0FA5) BSC.SDCR.LONG = 0x00000808;

/*  RAM clear from Ac000000 to Ac0fffff */
    for (addr = 0xAC000000; addr<0xAC200000; addr+=4) (*(volatile long *)addr) = 0x00000000;

/*
  CPG.MCLKCR.BYTE = 0;
  CPG.MCLKCR.BIT.FLSCS  = 3;
  CPG.MCLKCR.BIT.FLDIVS = 7;
  CPG.FRQCR.WORD = 0;
  CPG.FRQCR.BIT.CKOEN = 1;
  CPG.FRQCR.BIT.STC   = 7;
  CPG.FRQCR.BIT.IFC   = 7;
  CPG.FRQCR.BIT._PFC  = 7;

  HUDI.SDIR.WORD = 0;
  HUDI.SDIR.BIT.TI = 255;
  HUDI.SDID = 0;

  WDT.READ.WTCNT = 0;
  WDT.READ.WTCSR.BYTE = 0;
  WDT.READ.WTCSR.BIT.OVF  = 1;
  WDT.READ.WTCSR.BIT.WTIT = 1;
  WDT.READ.WTCSR.BIT.WOVF = 1;
  WDT.READ.WTCSR.BIT.IOVF = 1;
  WDT.READ.WTCSR.BIT.CKS  = 7;
  WDT.WRITE.WTCNT = 0;
  WDT.WRITE.WTCSR = 0;
*/
}
