/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Wed, Apr 22, 2009                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :SH7619                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  


#include	<machine.h>
#include	<_h_c_lib.h>
//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()
#include	"typedefine.h"
#include	"stacksct.h"
//#include	<ios>						// Remove the comment when you use ios
//_SINT ios::Init::init_cnt;				// Remove the comment when you use ios

#define SR_Init    0x000000F0
//#define SR_Init    0x00000040
#define INT_OFFSET 0x10

extern _UINT INT_Vectors;

#ifdef __cplusplus
extern "C" {
#endif
void PowerON_Reset_PC(void);
void Manual_Reset_PC(void);
void main(void);
#ifdef __cplusplus
}
#endif

//#ifdef __cplusplus				// Enable I/O in the application(both SIM I/O and hardware I/O)
//extern "C" {
//#endif
//extern void _INIT_IOLIB(void);
//extern void _CLOSEALL(void);
//#ifdef __cplusplus
//}
//#endif

//extern void srand(_UINT);		// Remove the comment when you use rand()
//extern _SBYTE *_s1ptr;				// Remove the comment when you use strtok()
		
#ifdef __cplusplus				// Use Hardware Setup
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif
	
extern void _CALL_INIT(void);
extern void _CALL_END(void);

#pragma section ResetPRG

void ProgCopy(void)
{
	unsigned int *src;
	unsigned int *dst;
	int len;

	src = (unsigned int *)__sectop("P");
	dst = (unsigned int *)__sectop("X");
	len = __secsize("P"); 

	if(dst != src)
    {
        while(len > 0)
        {
            *dst++ = *src++;

            len -= 4;
        }
    }

}

#pragma entry PowerON_Reset_PC

void PowerON_Reset_PC(void)
{ 
	set_vbr((void *)((_UBYTE *)&INT_Vectors - INT_OFFSET));

//	_CALL_INIT();					// Remove the comment when you use global class object

//	_INIT_IOLIB();					// Enable I/O in the application(both SIM I/O and hardware I/O)

//	errno=0;						// Remove the comment when you use errno
//	srand((_UINT)1);					// Remove the comment when you use rand()
//	_s1ptr=NULL;					// Remove the comment when you use strtok()

	HardwareSetup();				// Use Hardware Setup

	ProgCopy();

    _INITSCT();

	set_cr(SR_Init);

	main();

//	_CLOSEALL();					// Close I/O in the application(both SIM I/O and hardware I/O)
	
	_CALL_END();					// Remove the comment when you use global class object

	sleep();
}

