//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _DAC_H_
#define _DAC_H_

#include <TinyCLR_Interop.h>
struct Library_DAC_NXP_Interop_DAC
{
    TINYCLR_NATIVE_DECLARE(Initialize___VOID__I2);
    TINYCLR_NATIVE_DECLARE(Uninitialize___VOID);
    TINYCLR_NATIVE_DECLARE(On___VOID);
    TINYCLR_NATIVE_DECLARE(Off___VOID);
    TINYCLR_NATIVE_DECLARE(get_Enabled___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(set_Enabled___VOID__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(AddFrame___VOID__SZARRAY_I2__I4);
    TINYCLR_NATIVE_DECLARE(AddFrame___VOID__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(GetBufferLevel___I4);
    TINYCLR_NATIVE_DECLARE(GetFramesLeft___I4);
    TINYCLR_NATIVE_DECLARE(GetBufferFrameCapacity___U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_DAC;

#endif  //_DAC_H_
