//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "DAC.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_DAC_NXP_Interop_DAC::Initialize___VOID__I2,
    Library_DAC_NXP_Interop_DAC::Uninitialize___VOID,
    Library_DAC_NXP_Interop_DAC::On___VOID,
    Library_DAC_NXP_Interop_DAC::Off___VOID,
    Library_DAC_NXP_Interop_DAC::get_Enabled___BOOLEAN,
    Library_DAC_NXP_Interop_DAC::set_Enabled___VOID__BOOLEAN,
    Library_DAC_NXP_Interop_DAC::AddFrame___VOID__SZARRAY_I2__I4,
    Library_DAC_NXP_Interop_DAC::AddFrame___VOID__SZARRAY_U1__I4,
    Library_DAC_NXP_Interop_DAC::GetBufferLevel___I4,
    Library_DAC_NXP_Interop_DAC::GetFramesLeft___I4,
    Library_DAC_NXP_Interop_DAC::GetBufferFrameCapacity___U4,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_DAC =
{
    "DAC", 
    0xA6E680FC,
    method_lookup
};

