//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Netduino_IP_Interop.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_Netduino_IP_Interop_Netduino_IP_Interop_NetworkInterface::InitializeNetworkInterfaceSettings___VOID,
    Library_Netduino_IP_Interop_Netduino_IP_Interop_NetworkInterface::UpdateConfiguration___VOID__I4,
    NULL,
    Library_Netduino_IP_Interop_Netduino_IP_Interop_NetworkInterface::GetNetworkInterfaceCount___STATIC__I4,
    Library_Netduino_IP_Interop_Netduino_IP_Interop_NetworkInterface::GetNetworkInterface___STATIC__OBJECT__U4,
    Library_Netduino_IP_Interop_Netduino_IP_Interop_NetworkInterface::IPAddressFromString___STATIC__U4__STRING,
    NULL,
    Library_Netduino_IP_Interop_Netduino_IP_Interop_Wireless::UpdateConfiguration___STATIC__VOID__OBJECT__BOOLEAN,
    Library_Netduino_IP_Interop_Netduino_IP_Interop_Wireless::SaveAllConfigurations___STATIC__VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Netduino_IP_Interop =
{
    "Netduino.IP.Interop", 
    0xD8265967,
    method_lookup
};

