//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _NETDUINO_IP_INTEROP_H_
#define _NETDUINO_IP_INTEROP_H_

#include <TinyCLR_Interop.h>
#include <TinyCLR_Runtime.h>

struct Library_spot_net_native_Microsoft_SPOT_Net_NetworkInformation_NetworkInterface
{
    static const int FIELD___interfaceIndex       = 1;
    static const int FIELD___flags                = 2;
    static const int FIELD___ipAddress            = 3;
    static const int FIELD___gatewayAddress       = 4;
    static const int FIELD___subnetMask           = 5;
    static const int FIELD___dnsAddress1          = 6;
    static const int FIELD___dnsAddress2          = 7;
    static const int FIELD___networkInterfaceType = 8;
    static const int FIELD___macAddress           = 9;

    //--//

};

struct Library_spot_net_native_Microsoft_SPOT_Net_NetworkInformation_Wireless80211
{
    static const int FIELD__Authentication = 10;
    static const int FIELD__Encryption     = 11;
    static const int FIELD__Radio          = 12;
    static const int FIELD__PassPhrase     = 13;
    static const int FIELD__NetworkKey     = 14;
    static const int FIELD__ReKeyInternal  = 15;
    static const int FIELD__Ssid           = 16;
    static const int FIELD__Id             = 17;

    TINYCLR_NATIVE_DECLARE(UpdateConfiguration___STATIC__VOID__MicrosoftSPOTNetNetworkInformationWireless80211__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SaveAllConfigurations___STATIC__VOID);



    //--//

};

struct Library_Netduino_IP_Interop_Netduino_IP_Interop_NetworkInterface
{
    TINYCLR_NATIVE_DECLARE(InitializeNetworkInterfaceSettings___VOID);
    TINYCLR_NATIVE_DECLARE(UpdateConfiguration___VOID__I4);
    TINYCLR_NATIVE_DECLARE(GetNetworkInterfaceCount___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(GetNetworkInterface___STATIC__OBJECT__U4);
    TINYCLR_NATIVE_DECLARE(IPAddressFromString___STATIC__U4__STRING);

    //--//

};

struct Library_Netduino_IP_Interop_Netduino_IP_Interop_Wireless
{
    TINYCLR_NATIVE_DECLARE(UpdateConfiguration___STATIC__VOID__OBJECT__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SaveAllConfigurations___STATIC__VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Netduino_IP_Interop;

#endif  //_NETDUINO_IP_INTEROP_H_
