//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Netduino_IP_Interop.h"

HRESULT Library_Netduino_IP_Interop_Netduino_IP_Interop_Wireless::UpdateConfiguration___STATIC__VOID__OBJECT__BOOLEAN( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    TINYCLR_NOCLEANUP();
}

HRESULT Library_Netduino_IP_Interop_Netduino_IP_Interop_Wireless::SaveAllConfigurations___STATIC__VOID( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    TINYCLR_NOCLEANUP();
}
