/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Thu, Mar 04, 2010                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :SH2A                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  


#include    <machine.h>
#include    <_h_c_lib.h>
//#include  <stddef.h>                  // Remove the comment when you use errno
//#include  <stdlib.h>                  // Remove the comment when you use rand()
#include    "stacksct.h"

#define SR_Init    0x00000040
#define INT_OFFSET 0x10

extern UINT32 INT_Vectors;

#ifdef __cplusplus
extern "C" {
#endif
void PowerON_Reset_PC(void);
void Manual_Reset_PC(void);
extern void main(void);
#ifdef __cplusplus
}
#endif

//#ifdef __cplusplus                // Enable I/O in the application(both SIM I/O and hardware I/O)
//extern "C" {
//#endif
//extern void _INIT_IOLIB(void);
//extern void _CLOSEALL(void);
//#ifdef __cplusplus
//}
//#endif

//extern void srand(UINT32);     // Remove the comment when you use rand()
//extern INT8 *_s1ptr;                // Remove the comment when you use strtok()
        
#ifdef __cplusplus              // Use Hardware Setup
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif
    
//#ifdef __cplusplus            // Remove the comment when you use global class object
//extern "C" {                  // Sections C$INIT and C$END will be generated
//#endif
//extern void _CALL_INIT(void);
//extern void _CALL_END(void);
//#ifdef __cplusplus
//}
//#endif

#pragma section ResetPRG

#ifdef COPY_SECTION_P
void ProgCopy(void)
{
    unsigned int *src;
    unsigned int *dst;
    int len;

    src = (unsigned int *)__sectop("P");
    dst = (unsigned int *)__sectop("X");
    len = __secsize("P"); 

    if(dst != src)
    {
        while(len > 0)
        {
            *dst++ = *src++;

            len -= 4;
        }
    }
}
#endif

#pragma entry PowerON_Reset_PC

void PowerON_Reset_PC(void)
{
    /* ==== VBR setting ==== */
    set_vbr((void *)((char *)&INT_Vectors - INT_OFFSET));


    /* ==== HardwareSetup Function ==== */
    HardwareSetup();                /* Use Hardware Setup */

    /* ==== B and D sections initialization ==== */
#ifdef COPY_SECTION_P
    ProgCopy();
#endif

    _INITSCT();


    /* ==== Status Register setting ==== */
    set_cr(SR_Init);

    /* ==== Main function call ==== */
    main();

    /* ==== Sleep instruction execute ==== */
    sleep();
}

//#pragma entry Manual_Reset_PC     // Remove the comment when you use Manual Reset
void Manual_Reset_PC(void)  
{
}
