/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.c                                                */
/*  DATE        :Thu, Mar 04, 2010                                     */
/*  DESCRIPTION :Program of sbrk                                       */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  


#include <stddef.h>
#include <stdio.h>
#include "sbrk.h"

INT8  *sbrk(size_t size);

//const size_t _sbrk_size=		/* Specifies the minimum unit of	*/
					/* the defined heap area		*/

extern INT8 *_s1ptr;

#pragma pack 4
union HEAP_TYPE {
    INT32  dummy ;		/* Dummy for 4-byte boundary			*/
    INT8 heap[HEAPSIZE];	/* Declaration of the area managed by sbrk	*/
};

static union HEAP_TYPE heap_area ;
//static __X union HEAP_TYPE heap_area__X;              /* for DSP-C */
//static __Y union HEAP_TYPE heap_area__Y;              /* for DSP-C */
#pragma unpack

/* End address allocated by sbrk	*/
static INT8 *brk=(INT8 *)&heap_area;
//static __X INT8 *brk__X=(INT8 __X *)&heap_area__X;    /* for DSP-C */
//static __Y INT8 *brk__Y=(INT8 __Y *)&heap_area__Y;    /* for DSP-C */

/**************************************************************************/
/*     sbrk:Memory area allocation                                        */
/*          Return value:Start address of allocated area (Pass)           */
/*                       -1                              (Failure)        */
/**************************************************************************/
INT8  *sbrk(size_t size)                      /* Assigned area size   */
{
    INT8  *p;

    if(brk+size > heap_area.heap+HEAPSIZE){     /* Empty area size      */
        p = (INT8 *)-1;
    }
    else {
        p = brk;                                /* Area assignment      */
        brk += size;                            /* End address update   */
    }
    return p;
}

/**************************************************************************/
/*     sbrk:X Memory area allocation                                      */
/*          Return value:Start address of allocated area (Pass)           */
/*                       -1                              (Failure)        */
//*      When the dspc option is specified at compiling, remove // of     */
//*      the head of the line which has /* for DSP-C */ and add start     */
//*      options and add "$XB" and "$YB" to the start option at linkage.  */
/**************************************************************************/
//INT8 __X *sbrk__X(size_t size)        /* Assigned area size */      /* for DSP-C */
//{                                                                     /* for DSP-C */
//    __X INT8 *p;                                                    /* for DSP-C */
//                                                                      /* for DSP-C */
//    if (brk__X+size > heap_area__X.heap+HEAPSIZE) { /* Empty area size */ /* for DSP-C */
//        return (INT8 __X *)-1;                                      /* for DSP-C */
//    }                                                                 /* for DSP-C */
//                                                                      /* for DSP-C */
//    p = brk__X;                 /* Area assignment */                 /* for DSP-C */
//    brk__X += size;             /* End address update */              /* for DSP-C */
//    return p;                                                         /* for DSP-C */
//}                                                                     /* for DSP-C */

/**************************************************************************/
/*     sbrk:Y Memory area allocation                                      */
/*          Return value:Start address of allocated area (Pass)           */
/*                       -1                              (Failure)        */
//*      When the dspc option is specified at compiling, remove // of     */
//*      the head of the line which has /* for DSP-C */ and add start     */
//*      options and add "$XB" and "$YB" to the start option at linkage.  */
/**************************************************************************/
//INT8 __Y *sbrk__Y(size_t size)         /* Assigned area size */     /* for DSP-C */
//{                                                                     /* for DSP-C */
//    __Y INT8 *p;                                                    /* for DSP-C */
//                                                                      /* for DSP-C */
//    if (brk__Y+size > heap_area__Y.heap+HEAPSIZE) { /* Empty area size */ /* for DSP-C */
//        return (INT8 __Y *)-1;                                      /* for DSP-C */
//    }                                                                 /* for DSP-C */
//    p = brk__Y;                  /* Area assignment */                /* for DSP-C */
//    brk__Y += size;              /* End address update */             /* for DSP-C */
//    return p;                                                         /* for DSP-C */
//}                                                                     /* for DSP-C */
