//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "UsbHost.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbDevice::GetString___STRING__I4,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbDevice::ControlRequest___BOOLEAN__SZARRAY_U1__SZARRAY_U1,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbDevice::get_Configuration___MicrosoftSPOTHardwareUsbMicrosoftSPOTHardwareUsbClientConfiguration,
    NULL,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbDevice::get_Count___STATIC__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbPort::get_Status___MicrosoftSPOTHardwareUsbMicrosoftSPOTHardwareUsbClientUsbControllerPortState,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbPort::nativeStart___BOOLEAN,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbPort::nativeStop___BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbStream::nativeOpen___I4__I4__I4,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbStream::nativeClose___VOID,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbStream::nativeRead___I4__SZARRAY_U1__I4__I4,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbStream::nativeWrite___I4__SZARRAY_U1__I4__I4,
    Library_UsbHost_Microsoft_SPOT_Hardware_UsbHost_UsbStream::nativeFlush___VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_UsbHost =
{
    "UsbHost", 
    0x80089E99,
    method_lookup
};

