/***********************************************************************/
/*                                                                     */
/*  FILE        :intprg.c                                              */
/*  DATE        :Thu, Mar 04, 2010                                     */
/*  DESCRIPTION :Interrupt Program                                     */
/*  CPU TYPE    :SH2A                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  


#include <machine.h>
#include "vect.h"