/***********************************************************************/
/*                                                                     */
/*  FILE        :SH7216RSK.c                                           */
/*  DATE        :Thu, Mar 04, 2010                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  

#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//INT32 ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
