//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://localhost/ServiceHelloWCF", ConfigurationName = "IServiceHelloWCF")]
public interface IServiceHelloWCF
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/ServiceHelloWCF/IServiceHelloWCF/HelloWCF", ReplyAction = "http://localhost/ServiceHelloWCF/IServiceHelloWCF/HelloWCFResponse")]
    string HelloWCF(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceHelloWCFChannel : IServiceHelloWCF, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceHelloWCFClient : System.ServiceModel.ClientBase<IServiceHelloWCF>, IServiceHelloWCF
{

    public ServiceHelloWCFClient()
    {
    }

    public ServiceHelloWCFClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public ServiceHelloWCFClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ServiceHelloWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ServiceHelloWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string HelloWCF(string name)
    {
        return base.Channel.HelloWCF(name);
    }
}
