//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SECRETLABS_NETMF_DIAGNOSTICS_H_
#define _SECRETLABS_NETMF_DIAGNOSTICS_H_

#include <TinyCLR_Interop.h>
struct Library_SecretLabs_NETMF_Diagnostics_SecretLabs_NETMF_Diagnostics_Transport
{
    TINYCLR_NATIVE_DECLARE(TransportInterface_Set___STATIC__VOID__U1);
    TINYCLR_NATIVE_DECLARE(TransportInterface_Get___STATIC__U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SecretLabs_NETMF_Diagnostics;

#endif  //_SECRETLABS_NETMF_DIAGNOSTICS_H_
