//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SecretLabs_NETMF_Diagnostics.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_SecretLabs_NETMF_Diagnostics_SecretLabs_NETMF_Diagnostics_Transport::TransportInterface_Set___STATIC__VOID__U1,
    Library_SecretLabs_NETMF_Diagnostics_SecretLabs_NETMF_Diagnostics_Transport::TransportInterface_Get___STATIC__U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SecretLabs_NETMF_Diagnostics =
{
    "SecretLabs.NETMF.Diagnostics", 
    0x82C10CDA,
    method_lookup
};

