//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SecretLabs_NETMF_IO.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    Library_SecretLabs_NETMF_IO_SecretLabs_NETMF_IO_StorageDevice::SDSPI_Mount___STATIC__VOID__STRING__U4__U4__U4,
    Library_SecretLabs_NETMF_IO_SecretLabs_NETMF_IO_StorageDevice::SDSPI_Unmount___STATIC__VOID,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SecretLabs_NETMF_IO =
{
    "SecretLabs.NETMF.IO", 
    0xF29E77D5,
    method_lookup
};

